// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddTraining.Specs.Features.Files
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("View Shopping Cart Details", Description="\tIn order to place an order\r\n\tAs an online shopper\r\n\tI want to view my shopping c" +
        "art details before placing it", SourceFile="Files\\View Shopping Cart Details.feature", SourceLine=0)]
    public partial class ViewShoppingCartDetailsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "View Shopping Cart Details.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "View Shopping Cart Details", "\tIn order to place an order\r\n\tAs an online shopper\r\n\tI want to view my shopping c" +
                    "art details before placing it", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("View Shopping Cart Details", SourceLine=5)]
        public virtual void ViewShoppingCartDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View Shopping Cart Details", null, ((string[])(null)));
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "price",
                        "type",
                        "isimported"});
            table3.AddRow(new string[] {
                        "Kindle",
                        "500",
                        "Normal",
                        "true"});
            table3.AddRow(new string[] {
                        "Design Patterns",
                        "50",
                        "Book",
                        "false"});
#line 7
 testRunner.Given("I have the following products added to my cart:", ((string)(null)), table3, "Given ");
#line 11
 testRunner.When("I view my shopping cart details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "price",
                        "quantity",
                        "subtotal",
                        "Tax",
                        "note"});
            table4.AddRow(new string[] {
                        "Kindle",
                        "500",
                        "1",
                        "500",
                        "75",
                        "sales tax $50 + $25 import duty"});
            table4.AddRow(new string[] {
                        "Design Patterns",
                        "50",
                        "1",
                        "50",
                        "0",
                        "sales tax exempted and no import duty"});
#line 12
 testRunner.Then("My cart details should look like following:", ((string)(null)), table4, "Then ");
#line 16
 testRunner.And("The total price is $550", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("The tax total is $75", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("The grant total is $625", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
